id: A3569774E
title: 'A Garland of Vajra Words: A Prayer to the Guru'
type: translation
pechas:
- I3913906F
- IB47FF8B0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:36:10.519363
  last_modified_at: 2023-01-04 11:36:10.519373
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I3913906F/4AAF: D99D
  IB47FF8B0/654E: D99D
